### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Offirmo** [drcmda/react-contextual#2]
your project mentions the "Reacts new context API"

However, React doc has no mention of this.

It looks like a proposal, isn't it?

If yes, this is slightly misleading...

**Comment by drcmda** [comment]
@Offirmo good call! So, ..., React had the old broken context api, and they'd always ask you nicely to not rely on it, promising that it's going to get better. Since then they have made several rfc's until they have gotten to a point where they were happy with what they got.

The new context API is already merged in React and published as 16.3.0-alpha.0. The official release will come in a couple of days according to Dan Abramov.

This library uses a small polyfill (react-broadcast) meanwhile. I will remove it next week when react@16.3.0 comes out.

**Comment by Offirmo** [comment]
That's good news! Please write a blog post!

**Comment by drcmda** [comment]
@Offirmo that would be a first 😄got my worst grades in school for writing ...

**Comment by Twisterking** [comment]
Sorry to hijack this issue here but just to clarify:
You are saying that this is pretty much production ready right?! 😁 
If so this is great news for me ... for months I am looking for an excuse not to learn/use redux or mobx and stay true to the react core ... your awesome little library right here seems like the perfect fit! 😃 
Well done mate!

**Comment by drcmda** [comment]
@Twisterking sure, you can use it, it's production ready. 

>  for months I am looking for an excuse not to learn/use redux or mobx and stay true to the react core 

Yeah, it's a strange situation now. React now has this stuff covered out of the box. Just needed a little abstraction for ease of use.

**Comment by abenhamdine** [comment]
would be great to link the official announcement in the readme : https://reactjs.org/blog/2018/03/29/react-v-16-3.html#official-context-api

**Comment by drcmda** [comment]
@abenhamdine right, it's out now isn't it? I just came back from vacation and trying to keep up with everything. I'll take out react-broadcast too and finally review the pr you've made (thanks for that!)

**Comment by abenhamdine** [comment]
@drcmda yes it's totally stable and official in react 16.3
