### ISSUE TITLE
Typo on context check

### ISSUE THREAD

**Issue by msssk** [drcmda/react-contextual#30]
Lines [61-62 in store.js](https://github.com/drcmda/react-contextual/blob/2f4bec2f5fc3bd58bc044f1739b73f7b63407b86/src/store.js#L61-L62) don't seem to make sense:
```javascript
if (!store)
  this.store.context = id ? createNamedContext(id) : ProviderContext
```

Should 61 be changed?
```javascript
if (!store.context)
```

**Comment by drcmda** [comment]
looks good to me, if no external store is passed a context is created either by id or the default.

**Comment by smeijer** [comment]
Looks good indeed; The issue just needs a little more context.

https://github.com/drcmda/react-contextual/blob/2f4bec2f5fc3bd58bc044f1739b73f7b63407b86/src/store.js#L58:L62

`store` can still be `undefined` here, but `this.store` has been initialized one line before the `if`. Because there was no `store` provided to the contructor, the next thing to do is, assign this store a new `context`. Its like @drcmda writes, either done with `createNamedContext` or `ProviderContext` depending on the given arguments (`id`).
